### ISSUE TITLE
Vite 构建时报错 ReferenceError: DOMParser is not defined

### ISSUE THREAD

**Issue by Limoer96** [zh-lx/vitepress-demo-plugin#19]
看了下发现`genHtmlTemplate` 使用了`DOMParser`，在服务端渲染时会报错，请问怎么处理一下呢？

**Comment by zh-lx** [comment]
请问使用的 vitepress 版本是多少？

**Comment by Limoer96** [comment]
> 请问使用的 vitepress 版本是多少？

1.3.4

**Comment by zh-lx** [comment]
感谢反馈，已在 `1.0.1` 版本中修复了该问题
