### ISSUE TITLE
配合vitepress打包之后，没有加载的demo组件

### ISSUE THREAD

**Issue by ainuo5213** [zh-lx/vitepress-demo-plugin#23]
目前我遇到的问题是打包之后本地预览有预览的demo。但是部署到nginx上就没有预览的demo了。目前更换了另外一个预览插件，打包之后部署到nginx上是有预览的demo的。但个人还是很希望用这个一个，样式、功能都更加齐全

**Comment by zh-lx** [comment]
方便提供一个可复现的仓库看一下不？

**Comment by ainuo5213** [comment]
> 方便提供一个可复现的仓库看一下不？

公司内部的项目，提供不了。您这边打包出来放到服务器上是可以的么

**Comment by zh-lx** [comment]
可能是因为资源未加载完所以还未渲染完成？
<img width="1057" alt="image" src="https://github.com/user-attachments/assets/9e65824a-02be-4eb6-a983-314ee4cefa73">

**Comment by zh-lx** [comment]
> 可能是因为资源未加载完所以还未渲染完成？ <img alt="image" width="1057" src="https://private-user-images.githubusercontent.com/73059627/383937993-9e65824a-02be-4eb6-a983-314ee4cefa73.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyMTUxMTMsIm5iZiI6MTczMTIxNDgxMywicGF0aCI6Ii83MzA1OTYyNy8zODM5Mzc5OTMtOWU2NTgyNGEtMDJiZS00ZWI2LWE5ODMtMzE0ZWU0Y2VmYTczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEwVDA1MDAxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0MDk1NzA2MWUzN2ZlMzM4ZGM5NjI4YzcxMTQzZmQ4NTIxOTU1OTk5OTc3MmJmMjBjNzZiOGUzNDhmYzA1YjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.w3yVUVElIG0JEuWia4QZTtvotRC6VGk-CYmOso2Xsgo">

暂时判断为这个原因，是正常现象，关闭此 issue，如有其他问题欢迎再反馈
