### ISSUE TITLE
能否像Antdv文档一样，支持组件的JS/TS代码切换展示？

### ISSUE THREAD

**Issue by isixe** [zh-lx/vitepress-demo-plugin#28]
Ant Design Vue的文档提供了一个代码切换按钮，点击后可以切换组件的两种写法。

我一直再找vitepress能够展示多框架组件代码的方法，直到这个插件出现，毫无疑问这个是最合适的。

我想，提供二选一的展示比起固定的写法会更友好一些，如果能加上这个可选功能，很感谢。

**Comment by zh-lx** [comment]
好的，预计本周会支持多文件代码展示，可以适配这个功能

**Comment by zh-lx** [comment]
已在 `1.1.0` 版本中支持了该功能，可以参照 [多文件代码展示](https://vitepress-demo.fe-dev.cn/guide/advance.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E5%B1%95%E7%A4%BA) 进行配置
