### ISSUE TITLE
当项目路径中含有 `.` 时，在一个md文件中使用多个 <demo />提示报错

### ISSUE THREAD

**Issue by admin1949** [zh-lx/vitepress-demo-plugin#39]
![image](https://github.com/user-attachments/assets/67524609-fddf-4d38-a96a-9e7fc033a1b9)
从117行代码的逻辑分析，代码假定了整个文件路径中只包含一个 `.` 当路径中有多个`.`时，导致构造出来的短路径相同，最终导致vue/compiler-sfc编译代码报错

**Comment by zh-lx** [comment]
感谢反馈及 PR，已合入 `1.1.2` 版本中发布
