### ISSUE TITLE
Module "path" has been externalized for browser compatibility

### ISSUE THREAD

**Issue by nixwai** [zh-lx/vitepress-demo-plugin#43]
demo：https://stackblitz.com/edit/vitejs-vite-6kxdsh?file=markdown-examples.md

pnpm docs:build

warning:
[plugin:vite:resolve] [plugin vite:resolve] Module "path" has been externalized for browser compatibility, imported by "D:/Project/vitepress-demo-plugin-example/node_modules/.pnpm/vitepress-demo-plugin@1.1.3_vitepress@1.5.0_@algolia+client-search@5.15.0_postcss@8.4.49_sear_pavxhmkvtvqjlji4h23q2hbvhe/node_modules/vitepress-demo-plugin/dist/index.js". See https://vite.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
[plugin:vite:resolve] [plugin vite:resolve] Module "fs" has been externalized for browser compatibility, imported by "D:/Project/vitepress-demo-plugin-example/node_modules/.pnpm/vitepress-demo-plugin@1.1.3_vitepress@1.5.0_@algolia+client-search@5.15.0_postcss@8.4.49_sear_pavxhmkvtvqjlji4h23q2hbvhe/node_modules/vitepress-demo-plugin/dist/index.js". See https://vite.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.

**Comment by zh-lx** [comment]
感谢反馈，已在 `1.2.1` 版本中修复该问题，欢迎安装新版本体验
