### ISSUE TITLE
代码的高亮建议换正常的色，看着眼睛很不舒服，酸酸的。

### ISSUE THREAD

**Issue by InfernalAzazel** [zh-lx/vitepress-demo-plugin#44]
![image](https://github.com/user-attachments/assets/3758e855-4217-4d0b-86bd-90ae233bd47b)

**Comment by zh-lx** [comment]
已在 `1.2.0` 版本中更改了默认配色，并支持了用户自定义选择 `highlight.js` 提供的主题色列表，参考 [代码主题](https://vitepress-demo.fe-dev.cn/guide/advance.html#%E4%BB%A3%E7%A0%81%E4%B8%BB%E9%A2%98)
