### ISSUE TITLE
添加vue="Demo.vue" html="demo.html"后，代码展开状态下切换文件，会导致代码高度显示不对

### ISSUE THREAD

**Issue by shen830** [zh-lx/vitepress-demo-plugin#49]
添加vue="Demo.vue" html="demo.html"参数后，代码展开状态下切换文件，会导致代码高度显示不对。
例如图中，先展开vue代码后，再展开的状态下点击切换到html代码，下面就会有一大片空白，高度没有更新；而且添加:vueFiles后先点击下面的demo.js文件再点击html代码也会代码高度显示不对。
`<demo
    vue="Demo.vue"
    html="demo.html"
    :vueFiles="['Demo.vue', 'demo.js']" 
    title="混合语法 DEMO"
    description="这是一个混合 demo 的示例，你可以使用 title 和 description 来指定 demo 的标题和描述"
    order="html,vue"
    select="vue"
    stackblitz="true" 
    codesandbox="true"
/>`
![GIF 2024-12-23 10-11-57](https://github.com/user-attachments/assets/fd574b77-0295-45ec-9604-9cfaef3428e8)

**Comment by zh-lx** [comment]
感谢反馈，已在 `1.2.1` 版本中修复该问题，欢迎安装新版本体验
